services:
  phonikud-tts:
    image: hanandyn/phonikud-tts:latest
    container_name: phonikud-tts
    ports:
      - "8880:8880"
    restart: unless-stopped
    mem_limit: 4g
    mem_reservation: 2g
    pull_policy: always
    environment:
      - API_USERNAME=maia
      - API_PASSWORD=DRPIUbSyD0BLrxb/RQ5DjTjO
